### ISSUE TITLE
Wywołania metod na categoryRepo w MockLibraryRepository używają refleksji

### ISSUE THREAD

**Issue by gwilkowicz** [almendar/WarszawScala-slick-day#11]
Cześć,

Konstrukcja val categoryRepo = new  {...} powoduje utworzenie obiektu typu Object {def persist(a: Category) ...}. To z kolei prowadzi do tego, że wywołując metody, np. persist, na obiekcie categoryRepo użyty zostanie mechanizm refleksji.

Proponuję zdefiniować klasę "CategoryRepo" i użyć jej do zainicjowania categoryRepo.

**Comment by almendar** [comment]
True story. Structural types jak by miało nie być końca świata ;) 

Początkowo wszystkie repa wyglądały tak samo, ale Rafał chciał zmian w sposobie ściągania kategorii ponieważ tworzą drzewko no i na szybko skasowałem nazwę klasy po new i tak zostało ;)

Chciało by Ci się zrobić PR? Jeden już widzę jest i zaraz go merguje, bo ładny!

**Comment by gwilkowicz** [comment]
Jasne. Wieczorem będzie gotowy.

**Comment by almendar** [comment]
Super!
