### ISSUE TITLE
Push zepsuł build

### ISSUE THREAD

**Issue by almendar** [almendar/WarszawScala-slick-day#13]
Brakuje zależności. Info na travis:
https://travis-ci.org/almendar/WarszawScala-slick-day/builds/56647280

**Comment by almendar** [comment]
Chociaż moment, u mnie się buduje. Spróbuje wystartować build jeszcze raz.

**Comment by rkrzewski** [comment]
Dodałem repo Typesafe, powinno pomóc.

**Comment by rkrzewski** [comment]
Nie pomogło, hmm. Tu podobne issue: https://github.com/sbt/sbt-less/issues/31

**Comment by rkrzewski** [comment]
Uff, b159b10 pomogło
