### ISSUE TITLE
Rozwijanie kategorii w firefox - 100% procesora

### ISSUE THREAD

**Issue by gwilkowicz** [almendar/WarszawScala-slick-day#9]
Cześć,

Po kliknięciu w "Category with children", na poziomie > 4,  mam 100% zużycia procesora, które spada po pewnym czasie, jednak im bardziej zagłębiam się w kategorie tym dłużej to trwa.

Problem występuje w firefoxie (36.0.4), w chrome nie mam tego problemu.

**Comment by almendar** [comment]
Z tymi drzewkami, to Rafał jak będzie miał czas. Przydzielę go, ale nie wiem na ile ma dobrej woli :)

**Comment by rkrzewski** [comment]
Na 99% wynika to z rekurencyjnego wywołania dyrektywny `ngInclude` w pliku [categoryItem.html](https://github.com/almendar/WarszawScala-slick-day/blob/master/src/main/assets/partial/categoryItem.html#L13)
Gdyby to nie była zabawkowa aplikacja, trzeba by zaatakować to w bardziej wymyślny sposób: http://stackoverflow.com/a/18609594/1909747
Ponieważ jednak spoktanie mamy za 2 dni skoncentruję się raczej na widokach szczegółów poszczególnych obiektów i akcjach dodawania / usuwania.
